// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package faq

import (
	"github.com/mailru/easyjson/jlexer"
	"github.com/mailru/easyjson/jwriter"
)

func (postQuestionRequest) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*postQuestionRequest) UnmarshalJSON([]byte) error        { return nil }
func (postQuestionRequest) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*postQuestionRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_postQuestionRequest *postQuestionRequest
