[server]
    host = "0.0.0.0"
    port = "8081"

[logger]
    level = "info"

[postgres]
    max_conns = 10
    min_conns = 3
    max_idle_conn_time = "5m"

[redis]
    host = "localhost"
    port = "6379"
    db = 0

[auth]
    access_token_lifetime = "15m"
    refresh_token_lifetime = "168h"