// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/Rasikrr/learning_platform/internal/domain/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetByTopicID mocks base method.
func (m *MockRepository) GetByTopicID(ctx context.Context, id string) ([]*entity.Quiz, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTopicID", ctx, id)
	ret0, _ := ret[0].([]*entity.Quiz)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTopicID indicates an expected call of GetByTopicID.
func (mr *MockRepositoryMockRecorder) GetByTopicID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTopicID", reflect.TypeOf((*MockRepository)(nil).GetByTopicID), ctx, id)
}

// GetByTopicIDs mocks base method.
func (m *MockRepository) GetByTopicIDs(ctx context.Context, ids []string) ([]*entity.Quiz, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTopicIDs", ctx, ids)
	ret0, _ := ret[0].([]*entity.Quiz)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTopicIDs indicates an expected call of GetByTopicIDs.
func (mr *MockRepositoryMockRecorder) GetByTopicIDs(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTopicIDs", reflect.TypeOf((*MockRepository)(nil).GetByTopicIDs), ctx, ids)
}
